[package]
name = "pickaxe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
dialoguer = "0.11.0"
reqwest = {version = "0.12.15", features = ["blocking", "json"] }
serde = {version = "1.0.219", features = ["derive"] }
